### PR TITLE
Fix Python 3.8 syntax warnings

### PR DESCRIPTION
**Pull request by jcjones**

### CODE REVIEW

**Comment by martinthomson** [comment]
Hard to see the syntax fixes, but I assume that these are OK.

Is it worth adding CI for keeping files formatted?

**Comment by jcjones** [comment]
It's worth it, I just need to copy in the circleci configs I have laying around...

**Comment by martinthomson** [comment]
I don't know if we can use GitHub Actions, but the learning curve is steeper.

**Comment by jcjones** [comment]
This is now _only_ the python38 updates. I'm opening a separate review for the Black and CircleCI commit now.

**Pull request merged**
